language: node_js
node_js:
    - "4"
    - "4.3" # version used by AWS Lambda
    - "6"

install:
    - make install-sedy

script: make test

cache:
    directories:
        sedy/node_modules

branches:
  only:
    - master
